name: mnist_xs
dataset: mnist

# training
epochs: 100
warmup_steps: 0.1
batch_size: 16
accumulate_grad_batches: 4

learning_rate: 0.0003

# architecture 
embed_dim: 64
num_heads: 4
num_layers: 16
num_positions: 512
num_vocab: 3
tree_depth: 6
spatial_dim: 2

gpus: 1
precision: 16
