name: shapenet_single_conv

# data
dataset: shapenet
subclass: chair
resolution: 32
spatial_dim: 3
num_vocab: 3

# architecture
embedding: single_conv_A
head: single_conv_A
architecture: encoder_decoder
attention: basic
num_positions: 1024
embed_dim: 64
num_layers: 8
num_heads: 4

# training
loss_function: cross_entropy
epochs: 1000
warmup_steps: 0.1
batch_size: 32
accumulate_grad_batches: 1
learning_rate: 0.0003

# hardware
gpus: 8
precision: 32

# logging
log_gpu: 'min_max'
log_learning_rate: True
log_gradient: True
log_weights_and_biases: False
parameter_search: False