name: shapenet_xs

# data
dataset: shapenet
subclass: chair
num_positions: 4096
num_vocab: 3
tree_depth: 6
spatial_dim: 3

# architecture
attention: basic_ancestor
embed_dim: 64
num_layers: 16
num_heads: 4

# training
loss_function: cross_entropy
epochs: 1000
warmup_steps: 0.02
batch_size: 1
accumulate_grad_batches: 1
learning_rate: 0.0003

# hardware
gpus: 8
precision: 32

# logging
log_gpu: 'min_max'
log_gradient: True
log_weights_and_biases: False
log_learning_rate: True
sample_images: False
parameter_search: False