name: shapenet_debug

# data
dataset: shapenet
subclass: basket
resolution: 32
spatial_dim: 3
num_vocab: 3

# architecture
embedding: concat_B
head: split_B
architecture: autoencoder
attention: none
num_positions: 1024
embed_dim: 64
num_layers: 8
num_heads: 4

# training
loss_function: cross_entropy
val_loss_function: cross_entropy
epochs: 1000
warmup_steps: 0.1
batch_size: 8
accumulate_grad_batches: 1
learning_rate: 0.0003

# hardware
gpus: 1
precision: 32

# logging
log_gpu: 'min_max'
log_learning_rate: True
log_gradient: False
log_weights_and_biases: False
parameter_search: False