name: shapenet_debug
# pretrained: None

# data
dataset: shapenet
subclass: chair
transform: [scaling, warping, linear_max_res]
position_encoding: intertwined
resolution: 64
spatial_dim: 3
num_vocab: 3

# architecture
architecture: encoder_only
embedding: [composite_A]
head: [composite_A]

# attention
attention: basic
num_positions: 2048
embed_dim: 512
num_layers: 8
num_heads: 8

# training
loss_function: cross_entropy
val_loss_function: cross_entropy
epochs: 97
warmup_steps: 0.1
batch_size: 1
accumulate_grad_batches: 1
learning_rate: 0.00003
dropout: 0.2

# hardware
gpus: 1
precision: 32

# logging
log_gpu: 'min_max'
log_gradient: False
log_weights_and_biases: False
log_learning_rate: True
parameter_search: False