name: shapenet_xxs

# data
dataset: shapenet
subclass: chair
num_positions: 4096
num_vocab: 3
tree_depth: 6
spatial_dim: 3

# architecture
attention: basic_full
embed_dim: 16
num_layers: 4
num_heads: 2

# training
loss_function: cross_entropy
epochs: 30
warmup_steps: 0.05
batch_size: 8
accumulate_grad_batches: 1
learning_rate: 0.001

# hardware
gpus: 1
precision: 32

# logging
log_gpu: 'min_max'
log_gradient: True
log_weights_and_biases: False
log_learning_rate: True
sample_images: False
parameter_search: False
