name: shapenet_xxs
dataset: shapenet

# training
epochs: 30
warmup_steps: 0.1
batch_size: 4
accumulate_grad_batches: 1

learning_rate: 0.001

# architecture 
embed_dim: 16
num_heads: 2
num_layers: 8
num_positions: 4096
num_vocab: 3
tree_depth: 6
spatial_dim: 3

gpus: 1
precision: 16
