name: shapenet_lra

# data
dataset: shapenet
subclass: chair
num_positions: 4096
num_vocab: 3
tree_depth: 6
spatial_dim: 3

# architecture
attention: fast_linear
embed_dim: 512
num_heads: 8
num_layers: 6

# training
loss_function: cross_entropy
epochs: 5
warmup_steps: 0.1
batch_size: 8
accumulate_grad_batches: 1
learning_rate: 0.05

# hardware
gpus: 1
precision: 32

# logging
log_gpu: 'min_max'
log_learning_rate: True
log_gradient: True
log_weights_and_biases: False
sample_images: False
parameter_search: False