name: shapenet_weighted_loss

# data
dataset: shapenet
subclass: chair
resolution: 32
spatial_dim: 3
num_vocab: 3

# architecture
embedding: concat_B
head: split_B
architecture: encoder_decoder
attention: basic
num_positions: 1024
embed_dim: 256
num_layers: 8
num_heads: 4

# training
loss_function: depth_cross_entropy_F
val_loss_function: cross_entropy
epochs: 100
warmup_steps: 0.1
batch_size: 16
accumulate_grad_batches: 1
learning_rate: 0.0003

# hardware
gpus: 8
precision: 32

# logging
log_gpu: 'min_max'
log_learning_rate: True
log_gradient: False
log_weights_and_biases: False
parameter_search: False