name: shapenet_xs

# data
dataset: shapenet
subclass: chair
resolution: 32
spatial_dim: 3
num_vocab: 3

# architecture
embedding: basic
head: generative_basic
architecture: encoder_decoder
attention: basic
num_positions: 2048
embed_dim: 64
num_layers: 8
num_heads: 4

# training
loss_function: cross_entropy
epochs: 100
warmup_steps: 0.02
batch_size: 2
accumulate_grad_batches: 1
learning_rate: 0.0003

# hardware
gpus: 8
precision: 32

# logging
log_gpu: 'min_max'
log_gradient: True
log_weights_and_biases: False
log_learning_rate: True
parameter_search: False