name: shapenet_autoencoder

# data
dataset: shapenet
subclass: chair
resolution: 32
spatial_dim: 3
num_vocab: 3

# architecture
embedding: substitution
head: substitution
architecture: autoencoder
attention: none
num_positions: 0
embed_dim: 256
num_layers: 0
num_heads: 0

# training
loss_function: cross_entropy
val_loss_function: cross_entropy
epochs: 10
warmup_steps: 0.1
batch_size: 8
accumulate_grad_batches: 1
learning_rate: 0.001

# hardware
gpus: 1
precision: 32

# logging
log_gpu: 'min_max'
log_learning_rate: True
log_gradient: False
log_weights_and_biases: False
parameter_search: False